# Generated by Django 4.0.3 on 2022-03-25 18:40

from django.db import migrations, models
import django.utils.timezone
import package_app.models.package
import package_app.models.service


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.CharField(blank=True, default='', max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=django.utils.timezone.now, max_length=30)),
                ('price', models.CharField(blank=True, default=django.utils.timezone.now, max_length=30)),
                ('details', models.JSONField(blank=True, default=package_app.models.package.default_info_field)),
                ('service_ids', models.JSONField(blank=True, default=package_app.models.package.default_info_field)),
                ('status', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.CharField(blank=True, default='', max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=django.utils.timezone.now, max_length=30)),
                ('price', models.CharField(blank=True, default=django.utils.timezone.now, max_length=30)),
                ('details', models.JSONField(blank=True, default=package_app.models.service.default_info_field)),
                ('view_order', models.CharField(default=False, max_length=30)),
                ('status', models.BooleanField(blank=True, default=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
