# Generated by Django 4.0.3 on 2022-03-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_app', '0003_remove_service_details_remove_service_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
