# Generated by Django 4.0.3 on 2022-03-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_app', '0004_alter_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
