# Generated by Django 4.0.3 on 2022-03-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_app', '0006_alter_package_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
