# Generated by Django 4.0.3 on 2022-03-26 09:53

from django.db import migrations, models
import package_app.models.service


class Migration(migrations.Migration):

    dependencies = [
        ('package_app', '0007_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.JSONField(blank=True, default=package_app.models.service.default_info_field),
        ),
    ]
