# Generated by Django 4.0.3 on 2022-03-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_app', '0013_alter_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
