# Generated by Django 4.0.3 on 2022-03-26 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package_app', '0015_alter_service_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='names',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='price',
            new_name='total_price',
        ),
    ]
