# Generated by Django 4.0.3 on 2022-03-26 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package_app', '0016_rename_name_service_names_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Package',
        ),
    ]
